### ISSUE TITLE
Undefined identifier

### ISSUE THREAD

**Issue by IngwiePhoenix** [mrcarlberg/objj-runtime#1] opened 2019-02-18 15:26 UTC
Hello :)

Honestly, I had no real good idea for a name for this issue... So, I will let code talk for me instead:

```
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ objj test.j
../test.j:14
    (Speaker.isa.method_msgSend["speak"] || _objj_forward)(Speaker, "speak");
                               ^

TypeError: Cannot read property 'speak' of undefined
    at main (../test.j:14:32)
    at Object.exports.run (/usr/local/lib/node_modules/objj-runtime/lib/objective-j.js:4389:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/objj-runtime/bin/objj:3:31)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ objjc ./test.j --ecma5 -o test.js
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ cat test.js
{var the_class = objj_allocateClassPair(Nil, "Speaker"),
meta_class = the_class.isa;objj_registerClassPair(the_class);
class_addMethods(meta_class, [new objj_method(sel_getUid("speak"), function $Speaker__speak(self, _cmd)
{
    console.log("Hello!");
}

,["id"])]);
}
function main(args, namedArgs)
{
    (Speaker.isa.method_msgSend["speak"] || _objj_forward)(Speaker, "speak");
}
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ cat test.j
@implementation Speaker {}
+(id) speak {
  console.log("Hello!");
}
@end

function main(args, namedArgs) {
  [Speaker speak];
}
```

Why is `Speaker` not being defined as a variable?

Thanks in advance!

Kind regards,
Ingwie

**Comment by mrcarlberg** [comment] 2019-02-18 15:37
I can run your test file on my MacBook Pro.

So, I will build a fresh version of Cappuccino 1.0.0 and install a fresh version of objj-runtime from npm. I will use the instructions in the README file to check if anything is broken. I will do this tomorrow.

**Comment by IngwiePhoenix** [comment] 2019-02-18 15:42
This is what NPM gave me:
```
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ cat node_modules/objj-runtime/package.json | grep version
  "version": "0.1.10"
```

What I did not do was to copy a Cappucchino framework as I just want to see if the baseline works - I will get into using Cappuccino when I have that working. :)

**Comment by mrcarlberg** [comment] 2019-02-19 13:46
There was a miss match between the objj-compiler and the Objective-J framework that is included in objj-runtime. I also found some bugs when creating a class without a superclass in the Cappuccino runtime. I have also updated the dependencies to newer version of grunt etc.

Please try the latest published version on npm.

Thanks for letting me know about this.

**Comment by mrcarlberg** [comment] 2019-02-20 14:24
The bug I found when creating a class without a superclass is not a bug. A root class must implement the class method ```+ (void)initialize```. I will create a pull request so we get a proper error message instead of a crash when this happens.

**Comment by IngwiePhoenix** [comment] 2019-02-22 18:12
Hey!

I just got some free time to try out the updates, and this is what I encountered:

```
npm ERR! path /Users/Ingwie/Work/Triage/objj/node_modules/objj-runtime/bin/objc
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Ingwie/Work/Triage/objj/node_modules/objj-runtime/bin/objc'
npm ERR! enoent This is related to npm not being able to find a file.
```

I will see if I can still get a way to try this out :)

**Comment by IngwiePhoenix** [comment] 2019-02-22 18:57
Supplied #2 for a fix. :)

**Comment by mrcarlberg** [comment] 2019-02-22 21:21
I have published a new version with your patch. Thanks!

**Comment by IngwiePhoenix** [comment] 2019-02-22 21:24
Found another error:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/T/objj $ ./node_modules/objj-runtime/bin/objjc test.j 
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../lib/objective-j/compiler'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Ingwie/Work/Triage/objj/node_modules/objj-runtime/bin/objjc:3:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

Is your build process outputting the code to the right location or is that path actually correct? :)

**Comment by mrcarlberg** [comment] 2019-02-22 22:09
It is the wrong path for this tool. objjc is still under development so please use objjj to run your code instead. I will fix it next week.

**Comment by IngwiePhoenix** [comment] 2019-02-22 23:03
And it works! :)

Can't wait to use `objjc` to actually see the output that is being generated. But hey, at least I can run something and play around with ObjJ alltogether! Thank you for your support here :)

**Comment by mrcarlberg** [comment] 2024-09-21 09:02
I will close this as all issues have been solved.

**Closed as completed by mrcarlberg** 2024-09-21 09:02 UTC
